### ISSUE TITLE
Wrong Typesetting of Units

### ISSUE THREAD

**Issue by mzuenni** [nwerc/docs#2]
Right now the style guide says we should typeset units like ```$1\text{ cm}$```. However, this looks incredibly ugly and is also in conflict with the NIST recommendation and incompatible with the siunitx latex package. IMO we should change this either to ```$1\,\text{cm}$``` or directly to ```\SI{1}{\meter}```.

**Comment by mpsijm** [comment]
I would be in favour of using the `siunitx` package, provided we explain somewhere how to use it (could be a collapsible section with common examples and/or a link to proper documentation). I've always used that package with pleasure in other projects :slightly_smiling_face:

**Comment by mzuenni** [comment]
It looks like the gitlab markdown renderer does not support this: $\SI{3}{\cm\per\second\squared}$ (`$\SI{3}{\cm\per\second\squared}$`)

**Comment by mpsijm** [comment]
> It looks like the gitlab markdown renderer does not support this: $\SI3\cm\per\second\squared$ (`$\SI{3}{\cm\per\second\squared}$`)

I don't think this (or any) Markdown LaTeX renderer includes the `siunitx` package :stuck_out_tongue: But that's fine, we can just write the commands in monospace :slightly_smiling_face:

**Comment by RagnarGrootKoerkamp** [comment]
My only worry is how portable this will be for kattis export. Otherwise sgtm

**Comment by mpsijm** [comment]
It's not portable unfortunately, but we could add it to https://github.com/Kattis/problemtools/blob/develop/problemtools/templates/latex/problemset.cls :stuck_out_tongue: 

Additionally, their HTML renderer probably also doesn't support this :thinking:

**Comment by RagnarGrootKoerkamp** [comment]
Yeah I'm exactly worried about the HTML conversion. But we can use it ourselves anyway and backport where needed I suppose.

**Comment by mzuenni** [comment]
we could also not use the siunitx package directly but typeset it in the same way i.e. `$<value>\,\mathrm{<unit>}$`.

**Comment by mpsijm** [comment]
Assuming you took that from the `siunitx` implementation, sounds good to me :slightly_smiling_face: Then we don't have to backport for Kattis, and it would also avoid the issue that non-LaTeX-savvy people would have to learn yet another package :stuck_out_tongue:
